# Generated by Django 4.2.4 on 2023-08-10 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bot_channel_usage_delete_member_remove_cookie_bot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
