# Generated by Django 4.2.4 on 2023-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_channel_channel_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_reset',
            field=models.DateTimeField(blank=True),
        ),
    ]
