# Generated by Django 4.2.4 on 2023-08-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_channel_channel_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='channel',
            field=models.IntegerField(),
        ),
    ]
