# Generated by Django 4.2.4 on 2023-08-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usage_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='channel',
            new_name='channel_id',
        ),
    ]
