# Generated by Django 4.2.4 on 2023-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_channel_usage_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
