# Generated by Django 4.2.4 on 2023-08-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cookie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
