# Generated by Django 4.2.4 on 2023-08-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cookie_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='add_date',
            new_name='date',
        ),
    ]
