# Generated by Django 4.2.4 on 2023-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_add_date_cookie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
