# Generated by Django 4.2.4 on 2023-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cookie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
