# Generated by Django 4.2.4 on 2023-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cookie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
