# Generated by Django 3.2.25 on 2025-02-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(unique=True)),
                ('channel_limit', models.IntegerField()),
                ('channel_reset', models.IntegerField()),
                ('channel_next_reset', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_name', models.CharField(max_length=255)),
                ('cookie_text', models.TextField()),
                ('cookie_date', models.CharField(max_length=255)),
                ('cookie_count', models.IntegerField(default=0)),
                ('cookie_limit', models.IntegerField(default=20)),
                ('cookie_status', models.BooleanField(default=True)),
                ('cookie_is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_user_id', models.IntegerField()),
                ('member_channel_id', models.IntegerField()),
                ('member_usage_left', models.IntegerField()),
            ],
        ),
    ]
