# Generated by Django 4.2.4 on 2023-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='count',
            new_name='cookie_count',
        ),
        migrations.RenameField(
            model_name='cookie',
            old_name='date',
            new_name='cookie_date',
        ),
        migrations.RenameField(
            model_name='cookie',
            old_name='name',
            new_name='cookie_name',
        ),
        migrations.RenameField(
            model_name='cookie',
            old_name='cookie',
            new_name='cookie_text',
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='status',
        ),
        migrations.AddField(
            model_name='cookie',
            name='cookie_status',
            field=models.BooleanField(default=True),
        ),
    ]
