# Generated by Django 4.2.4 on 2023-08-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_count_cookie_cookie_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='cookie_date',
            field=models.CharField(default='18-08-2023 15:49:25', max_length=255),
        ),
    ]
