# Generated by Django 4.2.4 on 2023-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_cookie_cookie_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='channel_id',
            new_name='usage_channel_id',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='usage',
            new_name='usage_count',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='user_id',
            new_name='usage_user_id',
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie_date',
            field=models.CharField(default='21.08.2023 09:24:53', max_length=255),
        ),
    ]
