# Generated by Django 4.2.4 on 2023-08-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_channel_id_usage_usage_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_next_reset',
            field=models.CharField(default='21.08.2023 14:42:27', max_length=255),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie_date',
            field=models.CharField(default='21.08.2023 14:42:27', max_length=255),
        ),
    ]
