# Generated by Django 4.2.4 on 2023-08-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_channel_channel_next_reset_alter_cookie_cookie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_next_reset',
            field=models.CharField(default='21.08.2023 14:42:36', max_length=255),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie_date',
            field=models.CharField(default='21.08.2023 14:42:36', max_length=255),
        ),
    ]
