# Generated by Django 4.2.4 on 2023-09-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_channel_channel_next_reset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='usage_count',
            new_name='usage_left',
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_next_reset',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie_date',
            field=models.CharField(max_length=255),
        ),
    ]
