# Generated by Django 4.2.4 on 2023-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_usage_count_usage_usage_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='cookie_is_current',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookie',
            name='cookie_limit',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='cookie',
            name='cookie_priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
