# Generated by Django 4.2.4 on 2023-09-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_cookie_cookie_is_current_cookie_cookie_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='cookie_priority',
        ),
    ]
