# Generated by Django 4.2.4 on 2023-09-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_cookie_cookie_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usage',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='usage_channel_id',
            new_name='member_channel_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='usage_left',
            new_name='member_usage_left',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='usage_user_id',
            new_name='member_user_id',
        ),
    ]
