# Generated by Django 4.2.4 on 2023-08-11 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_cookie_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
